SELECT
  VENDEDORES.NOMBRE AS VENDEDOR,
  VENTAS.ARTICULO, 
  VENTAS.VENTA AS VENTA_TOTAL,
  VENTAS.UNIDADES,
  ULTIMO_DOCTO.ULTIMO_COSTO
FROM
(
  SELECT
    VENDEDOR_ID,
    ARTICULO_ID,
    ARTICULO,
    SUM(VENTA) AS VENTA,
    SUM(UNIDADES) AS UNIDADES
  FROM
  (
    SELECT 
      DOCTOS_VE.VENDEDOR_ID,
      DOCTOS_VE.TIPO_DOCTO,
      DOCTOS_VE.ESTATUS,
      DOCTOS_VE_DET.ARTICULO_ID,
      ARTICULOS.NOMBRE AS ARTICULO,
      CASE DOCTOS_VE.TIPO_DOCTO 
        WHEN 'D' THEN
          0 - SUM(DOCTOS_VE_DET.UNIDADES * DOCTOS_VE_DET.PRECIO_UNITARIO)
        WHEN 'F' THEN
          SUM(DOCTOS_VE_DET.UNIDADES * DOCTOS_VE_DET.PRECIO_UNITARIO)
      END AS VENTA,
      CASE DOCTOS_VE.TIPO_DOCTO 
        WHEN 'D' THEN
          0 - SUM(DOCTOS_VE_DET.UNIDADES)
        WHEN 'F' THEN
          SUM(DOCTOS_VE_DET.UNIDADES)
      END AS UNIDADES
    FROM
      DOCTOS_VE_DET
    INNER JOIN DOCTOS_VE ON (DOCTOS_VE_DET.DOCTO_VE_ID = DOCTOS_VE.DOCTO_VE_ID)
    INNER JOIN ARTICULOS ON (DOCTOS_VE_DET.ARTICULO_ID = ARTICULOS.ARTICULO_ID)
    WHERE
      DOCTOS_VE.FECHA BETWEEN '|FECHA_INICIO|' AND '|FECHA_FIN|' AND 
      DOCTOS_VE.APLICADO LIKE 'S'
    GROUP BY
      DOCTOS_VE.VENDEDOR_ID,
      DOCTOS_VE.TIPO_DOCTO,
      DOCTOS_VE.ESTATUS,
      DOCTOS_VE_DET.ARTICULO_ID,
      ARTICULOS.NOMBRE
  )
  GROUP BY
    ARTICULO,
    ARTICULO_ID,
    VENDEDOR_ID
) AS VENTAS

INNER JOIN

(
SELECT
  ARTICULO_ID, 
  ULTIMO_COSTO
FROM
  (
  SELECT
    ULTIMO_DOCTO.ARTICULO_ID, 
    DOCTOS_IN_DET.COSTO_UNITARIO AS ULTIMO_COSTO
    FROM
    (
      SELECT 
        DOCTOS_IN_DET.ARTICULO_ID,
        MAX(DOCTOS_IN_DET.DOCTO_IN_DET_ID) AS DOCTO_IN_DET_ID
      FROM
        DOCTOS_IN_DET
      WHERE
        DOCTOS_IN_DET.TIPO_MOVTO LIKE 'E'
      GROUP BY
        DOCTOS_IN_DET.ARTICULO_ID
      ) AS ULTIMO_DOCTO
    INNER JOIN DOCTOS_IN_DET ON DOCTOS_IN_DET.DOCTO_IN_DET_ID = ULTIMO_DOCTO.DOCTO_IN_DET_ID
  )
) AS ULTIMO_DOCTO

ON VENTAS.ARTICULO_ID = ULTIMO_DOCTO.ARTICULO_ID

INNER JOIN VENDEDORES ON VENTAS.VENDEDOR_ID = VENDEDORES.VENDEDOR_ID

WHERE VENDEDORES.VENDEDOR_ID IN (|VENDEDORES_IDS|)

ORDER BY
VENDEDORES.NOMBRE, 
ARTICULO